name: Coverage
on:
  push:
    branches:
      - main
jobs:
  codecov:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
      - name: Generate coverage report
        run: |
          cd frontend
          npm install
          npm install jest
          npm test -- --coverage --json --outputFile coverage.json
          cd ..
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: .
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./frontend/coverage.json
          flags: unittests
          name: codecov-umbrella
#          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true