name: Coverage
on:
  push:
    branches:
      - main
jobs:
  codecov:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Generate coverage report
        run: |
          cd frontend
          npm init --yes
          npm install --save-dev jest
          npm install
          npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}